updated welcome message
Fubinator/planning-poker-discord-bot pull request #39
Opened 2020-10-01 16:38 UTC by DevDaksh

Changed welcome message. This PR resolved #6. I couldn't find anything much relevant in the docs which should be added to welcome message. Added the stuff I thought was relevant

2020-10-01 17:13 UTC, Fubinator requested changes

2020-10-01 17:13 UTC, Fubinator commented on index.js
> +  console.log(client)
I think you can delete the log of the whole client. It just  bloats the output

2020-10-01 17:13 UTC, Fubinator commented on index.js
> +    message.channel.send(`"Welcome to planning poker"`);
Could you remove the backticks here?

2020-10-01 18:08 UTC, dawksh commented on index.js
> +  console.log(client)
oh I forgot that

2020-10-01 18:09 UTC, Fubinator commented on index.js
> +  console.log(client)
No worries!

2020-10-01 18:11 UTC, DevDaksh commented
maybe check the code now

2020-10-01 18:11 UTC, Fubinator approved these changes

2020-10-01 18:11 UTC, Fubinator commented
Looking good @DevDaksh, I'm merging this tomorrow. Thank you for your contribution!

2020-10-01 18:12 UTC, DevDaksh commented
Thanks for accepting!

2020-10-02 07:17 UTC, merged

2020-10-04 06:56 UTC, DevDaksh commented
Would you mind adding hacktober-accepted tag to this PR?